// src/App.tsx
import { useState, useEffect } from 'react';
import { getData } from './utils';
import type { ItemData } from './types';

function App() {
    const [temperature, setTemperature] = useState<ItemData[]>([]);
    const [precipitation, setPrecipitation] = useState<ItemData[]>([]);

    useEffect(() => {
        (async () => {
            setTemperature(await getData<ItemData>('../data/temperature.json'));
            setPrecipitation(await getData<ItemData>('../data/precipitation.json'));
        })();
    }, []);

    return (
        <div>
            <div>
                Temperature data length: {temperature.length}
                <details>
                    <summary>Temperature</summary>
                    {JSON.stringify(temperature)}
                </details>
            </div>
            <br />
            <div>
                Precipitation data length: {precipitation.length}
                <details>
                    <summary>Precipitation</summary>
                    {JSON.stringify(precipitation)}
                </details>
            </div>
        </div>
    );
}

export default App;

// src/App.vue
<script setup lang="ts">
    import { ref, onMounted } from 'vue';
    import { getData } from './utils';
    import type { ItemData } from './types';

    /** data */
    let temperature = ref<ItemData[]>([]);
    let precipitation = ref<ItemData[]>([]);

    onMounted(async () => {
        temperature.value = await getData<ItemData>('../data/temperature.json');
        precipitation.value = await getData<ItemData>('../data/precipitation.json');
    });
</script>

<template>
    <div>
        <div>
            Temperature data length: {{temperature.length}}
            <details>
                <summary>Temperature</summary>
                {{temperature}}
            </details>
        </div>
        <br>
        <div>
            Precipitation data length: {{precipitation.length}}
            <details>
                <summary>Precipitation</summary>
                {{precipitation}}
            </details>
        </div>
    </div>
</template>

<style scoped>
</style>
